language: node_js
node_js:
- node
install:
- npm install -g elm
script:
- sh ./scripts/build_example.sh
cache:
  directories:
  - example/elm-stuff/build-artifacts
env:
  global:
    secure: a6JpWdQQSdNweMqrkO7Q0L92lA04gtVTMXOrpltpiWqp4Z/jrs3amFnjYQlvcJxw5qYXzvg0BmcgPxiUk67b+j4qFZKTqyrrSsM5RXeIM8PzWvEDngi+5wLPXU3/PDjkpNFaUOciegtSZN8SBBpca+TK6vT3FwJsHJjjAfUtPgtH48YZpNHfOieCxiTFsv9ruZy3B3S+eBWSFKlcwrnGnJtG4coLy4veuHzMXYNU6XkaNkHT552BuCWD9ts+b+p48ls+hwgF84vY70OZfqfTFFfxZOoYKSctGHvI6gXFwFU5AR0v9Q9hlQdzjYHLNTMXSZAbjBw7xkF/IPTVLy8+kRN1Ri/4IqSLTfFTwJWoMgRxGq3IhSnaLkTQNoccbtpTX0SsF0MNwgrgECJ1B0svw426cS2i/ZcY8Wgpqkau2Ys3vvvhabmyqVDpsasZfcxd3YGwblPyGZStudLuELmtfkEasZW7WvN63w1r6SdiN6Ad7wsa5kwNY9U6OkFKjmxMl30RjPwfrOmF1b6Pd1lViBjK50nylNeF7dO7AkL+ttw+OEMM/LEqxILPwKEyxaUlxw6wNoE4HoYAamQgH4IQ0OzqcFoNMhBetO9Rbnfq4RF9G9LkCFEI/i/doCuh5gxwdarBoo7+HCrYxbC8IhQSvKhXZoOl2DDRWxj8oW1KGZc=
