language: node_js
node_js:
- node
install:
- npm install -g elm
script:
- sh ./scripts/build_example.sh
after_success:
- sh ./scripts/deploy.sh
cache:
  directories:
  - example/elm-stuff/build-artifacts
