language: node_js
node_js:
- node
install:
- npm install -g elm
- |
  if [ ! -d libsysconfcpus/bin ]; then
    git clone https://github.com/obmarg/libsysconfcpus.git;
    cd libsysconfcpus;
    ./configure --prefix=$TRAVIS_BUILD_DIR/libsysconfcpus;
    make && make install;
    cd ..;
  fi
script:
- sh ./scripts/build_example.sh
after_success:
- sh ./scripts/deploy.sh
cache:
  directories:
  - example/elm-stuff/build-artifacts
  - libsysconfcpus
  
